<a href="https://colab.research.google.com/github/thiselvan/files_and_json_assignment/blob/main/tutorial_session_14th_march.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""You are working as a data analyst at a retail company. Your manager has asked you to analyze customer purchasing behavior using a transactional orders database. You will load two real-world datasets into an in-memory SQLite database using Python, and write SQL queries to answer business questions involving aggregation, filtering, and table joins.
"""

'You are working as a data analyst at a retail company. Your manager has asked you to analyze customer purchasing behavior using a transactional orders database. You will load two real-world datasets into an in-memory SQLite database using Python, and write SQL queries to answer business questions involving aggregation, filtering, and table joins.\n'

In [ ]:
import pandas as pd
import sqlite3

DataSet Links

In [ ]:
customers_url = " https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/customers.csv"

orders_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/orders.csv"

In [ ]:
customers_df = pd.read_csv(customers_url)
orders_df = pd.read_csv(orders_url)

In [ ]:
conn = sqlite3.connect(":memory:")

In [ ]:
from numpy._core.defchararray import index
customers_df.to_sql("customers" , conn , index = False , if_exists="replace")
orders_df.to_sql("orders" , conn, index = False , if_exists="replace")

830

In [ ]:
orders_df[orders_df["freight"] > 50]

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,2,65.83,Hanari Carnes,Rua do Paço 67,Rio de Janeiro,RJ,05454-876,Brazil
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,2,51.30,Suprêmes délices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium
5,10253,HANAR,3,1996-07-10 00:00:00.000,1996-07-24 00:00:00.000,1996-07-16 00:00:00.000,2,58.17,Hanari Carnes,Rua do Paço 67,Rio de Janeiro,RJ,05454-876,Brazil
7,10255,RICSU,9,1996-07-12 00:00:00.000,1996-08-09 00:00:00.000,1996-07-15 00:00:00.000,3,148.33,Richter Supermarkt,Starenweg 5,Genève,NaN,1204,Switzerland
9,10257,HILAA,4,1996-07-16 00:00:00.000,1996-08-13 00:00:00.000,1996-07-22 00:00:00.000,3,81.91,HILARION-Abastos,Carrera 22 con Ave. Carlos Soublette #8-35,San Cristóbal,Táchira,5022,Venezuela
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,11059,RICAR,2,1998-04-29 00:00:00.000,1998-06-10 00:00:00.000,NaN,2,85.80,Ricardo Adocicados,Av. Copacabana 267,Rio de Janeiro,RJ,02389-890,Brazil
815,11063,HUNGO,3,1998-04-30 00:00:00.000,1998-05-28 00:00:00.000,1998-05-06 00:00:00.000,2,81.73,Hungry Owl All-Night Grocers,8 Johnstown Road,Cork,Co. Cork,NaN,Ireland
820,11068,QUEEN,8,1998-05-04 00:00:00.000,1998-06-01 00:00:00.000,NaN,2,81.75,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
822,11070,LEHMS,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,1,136.00,Lehmanns Marktstand,Magazinweg 7,Frankfurt a.M.,NaN,60528,Germany
824,11072,ERNSH,4,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,2,258.64,Ernst Handel,Kirchgasse 6,Graz,NaN,8010,Austria

In [ ]:
orders_df[(orders_df["customerID"] == "VINET") | (orders_df["customerID"] == "QUEEN")]

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
26,10274,VINET,6,1996-08-06 00:00:00.000,1996-09-03 00:00:00.000,1996-08-16 00:00:00.000,1,6.01,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
47,10295,VINET,2,1996-09-02 00:00:00.000,1996-09-30 00:00:00.000,1996-09-10 00:00:00.000,2,1.15,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
124,10372,QUEEN,5,1996-12-04 00:00:00.000,1997-01-01 00:00:00.000,1996-12-09 00:00:00.000,2,890.78,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
158,10406,QUEEN,7,1997-01-07 00:00:00.000,1997-02-18 00:00:00.000,1997-01-13 00:00:00.000,1,108.04,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
239,10487,QUEEN,2,1997-03-26 00:00:00.000,1997-04-23 00:00:00.000,1997-03-28 00:00:00.000,2,71.07,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
389,10637,QUEEN,6,1997-08-19 00:00:00.000,1997-09-16 00:00:00.000,1997-08-26 00:00:00.000,1,201.29,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
411,10659,QUEEN,7,1997-09-05 00:00:00.000,1997-10-03 00:00:00.000,1997-09-10 00:00:00.000,2,105.81,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
456,10704,QUEEN,6,1997-10-14 00:00:00.000,1997-11-11 00:00:00.000,1997-11-07 00:00:00.000,1,4.78,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
480,10728,QUEEN,4,1997-11-04 00:00:00.000,1997-12-02 00:00:00.000,1997-11-11 00:00:00.000,2,58.33,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
489,10737,VINET,2,1997-11-11 00:00:00.000,1997-12-09 00:00:00.000,1997-11-18 00:00:00.000,2,7.79,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
491,10739,VINET,3,1997-11-12 00:00:00.000,1997-12-10 00:00:00.000,1997-11-17 00:00:00.000,3,11.08,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
538,10786,QUEEN,8,1997-12-19 00:00:00.000,1998-01-16 00:00:00.000,1997-12-23 00:00:00.000,1,110.87,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
620,10868,QUEEN,7,1998-02-04 00:00:00.000,1998-03-04 00:00:00.000,1998-02-23 00:00:00.000,2,191.27,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
665,10913,QUEEN,4,1998-02-26 00:00:00.000,1998-03-26 00:00:00.000,1998-03-04 00:00:00.000,1,33.05,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
666,10914,QUEEN,6,1998-02-27 00:00:00.000,1998-03-27 00:00:00.000,1998-03-02 00:00:00.000,1,21.19,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
713,10961,QUEEN,8,1998-03-19 00:00:00.000,1998-04-16 00:00:00.000,1998-03-30 00:00:00.000,1,104.47,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil
820,11068,QUEEN,8,1998-05-04 00:00:00.000,1998-06-01 00:00:00.000,NaN,2,81.75,Queen Cozinha,Alameda dos Canàrios 891,Sao Paulo,SP,05487-020,Brazil

In [ ]:
query1 = """
SELECT
    CustomerID,
    COUNT(OrderID)     AS order_count,
    SUM(Freight)       AS total_freight,
    AVG(Freight)       AS avg_freight
FROM orders
GROUP BY CustomerID
ORDER BY total_freight DESC;
"""
result1 = pd.read_sql_query(query1, conn)
print(result1.head(10))

  customerID  order_count  total_freight  avg_freight
0      SAVEA           31        6683.70   215.603226
1      ERNSH           30        6205.39   206.846333
2      QUICK           28        5605.63   200.201071
3      HUNGO           19        2755.24   145.012632
4      RATTC           18        2134.21   118.567222
5      QUEEN           13        1982.70   152.515385
6      FOLKO           19        1678.08    88.320000
7      BERGS           18        1559.52    86.640000
8      FRANK           15        1403.44    93.562667
9      MEREP           13        1394.22   107.247692

In [ ]:
query_a = """
SELECT CustomerID, COUNT(OrderID) AS high_freight_orders
FROM orders
WHERE Freight > 50
GROUP BY CustomerID;
"""

result_a = pd.read_sql_query(query_a, conn)

In [ ]:
result_a

   customerID  high_freight_orders
0       ALFKI                    2
1       ANTON                    2
2       AROUT                    2
3       BERGS                   11
4       BLAUS                    1
..        ...                  ...
69      WANDK                    2
70      WARTH                    6
71      WELLI                    1
72      WHITC                    7
73      WOLZA                    1

[74 rows x 2 columns]

In [ ]:
query_b = """
SELECT CustomerID, SUM(Freight) AS total_freight
FROM orders
GROUP BY CustomerID
HAVING SUM(Freight) > 500;
"""


result_b = pd.read_sql_query(query_b, conn)

In [ ]:
query_inner = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID)  AS order_count,
    SUM(o.Freight)    AS total_freight
FROM customers c
INNER JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CompanyName, c.Country
ORDER BY total_freight DESC;
"""

In [ ]:
result_inner = pd.read_sql_query(query_inner, conn)

In [ ]:
result_inner

                      companyName  country  order_count  total_freight
0              Save-a-lot Markets      USA           31        6683.70
1                    Ernst Handel  Austria           30        6205.39
2                      QUICK-Stop  Germany           28        5605.63
3    Hungry Owl All-Night Grocers  Ireland           19        2755.24
4      Rattlesnake Canyon Grocery      USA           18        2134.21
..                            ...      ...          ...            ...
84         Galería del gastrónomo    Spain            5          37.98
85                    North/South       UK            3          37.59
86           Lazy K Kountry Store      USA            2          19.40
87  Laughing Bacchus Wine Cellars   Canada            3           9.92
88     Centro comercial Moctezuma   Mexico            1           3.25

[89 rows x 4 columns]

In [ ]:
query_left = """
SELECT
    c.CompanyName,
    c.Country,
    COUNT(o.OrderID)  AS order_count,
    SUM(o.Freight)    AS total_freight
FROM customers c
LEFT JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CompanyName, c.Country
ORDER BY total_freight DESC;
"""

In [ ]:
result_left  = pd.read_sql_query(query_left, conn)

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   orderID         830 non-null    int64
 1   customerID      830 non-null    object
 2   employeeID      830 non-null    int64
 3   orderDate       830 non-null    object
 4   requiredDate    830 non-null    object
 5   shippedDate     809 non-null    object
 6   shipVia         830 non-null    int64
 7   freight         830 non-null    float64
 8   shipName        830 non-null    object
 9   shipAddress     830 non-null    object
 10  shipCity        830 non-null    object
 11  shipRegion      323 non-null    object
 12  shipPostalCode  811 non-null    object
 13  shipCountry     830 non-null    object
dtypes: float64(1), int64(3), object(10)
memory usage: 90.9+ KB

In [ ]:
orders_df

,orderID,customerID,employeeID,orderDate,requiredDate,shippedDate,shipVia,freight,shipName,shipAddress,shipCity,shipRegion,shipPostalCode,shipCountry
0,10248,VINET,5,1996-07-04 00:00:00.000,1996-08-01 00:00:00.000,1996-07-16 00:00:00.000,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05 00:00:00.000,1996-08-16 00:00:00.000,1996-07-10 00:00:00.000,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-12 00:00:00.000,2,65.83,Hanari Carnes,Rua do Paço 67,Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08 00:00:00.000,1996-08-05 00:00:00.000,1996-07-15 00:00:00.000,1,41.34,Victuailles en stock,2 rue du Commerce,Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09 00:00:00.000,1996-08-06 00:00:00.000,1996-07-11 00:00:00.000,2,51.30,Suprêmes délices,Boulevard Tirou 255,Charleroi,NaN,B-6000,Belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05 00:00:00.000,1998-06-02 00:00:00.000,NaN,2,24.95,Pericles Comidas clásicas,Calle Dr. Jorge Cash 321,México D.F.,NaN,05033,Mexico
826,11074,SIMOB,7,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,2,18.44,Simons bistro,Vinbæltet 34,Kobenhavn,NaN,1734,Denmark
827,11075,RICSU,8,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,2,6.19,Richter Supermarkt,Starenweg 5,Genève,NaN,1204,Switzerland
828,11076,BONAP,4,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,2,38.28,Bon app',12 rue des Bouchers,Marseille,NaN,13008,France
829,11077,RATTC,1,1998-05-06 00:00:00.000,1998-06-03 00:00:00.000,NaN,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA

In [ ]:
import seaborn as sns
tips = sns.load_dataset("tips")

In [ ]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
sns.scatterplot(df , x )